// frontend/src/components/mdsItems.js
export const MDS_UPDRS_ITEMS = {
  part1: [
    { id: "1.1", question: "Cognitive Impairment", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.2", question: "Hallucinations and Psychosis", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.3", question: "Depressed Mood", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.4", question: "Anxious Mood", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.5", question: "Apathy", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.6", question: "Features of Dopamine Dysregulation Syndrome", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.7", question: "Sleep Problems", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.8", question: "Daytime Sleepiness", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.9", question: "Pain and Other Sensations", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.10", question: "Urinary Problems", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.11", question: "Constipation Problems", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.12", question: "Lightheadedness on Standing", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "1.13", question: "Fatigue", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
  ],
  part2: [
    { id: "2.1", question: "Speech", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.2", question: "Saliva & Drooling", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.3", question: "Chewing and Swallowing", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.4", question: "Eating Tasks", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.5", question: "Dressing", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.6", question: "Hygiene", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.7", question: "Handwriting", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.8", question: "Doing Hobbies and Other Activities", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.9", question: "Turning in Bed", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.10", question: "Tremor", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.11", question: "Getting Out of Bed, a Car, or a Deep Chair", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.12", question: "Walking and Balance", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "2.13", question: "Freezing", type: "patient", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
  ],
  part3: [
    { id: "3.1", question: "Speech", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.2", question: "Facial Expression", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.3", question: "Rigidity (Neck)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.4", question: "Finger Taps (Right)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.5", question: "Finger Taps (Left)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.6", question: "Hand Movements (Right)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.7", question: "Hand Movements (Left)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.8", question: "Pronation-Supination (Right)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.9", question: "Pronation-Supination (Left)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.10", question: "Toe Tapping (Right)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.11", question: "Toe Tapping (Left)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.12", question: "Leg Agility (Right)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.13", question: "Leg Agility (Left)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.14", question: "Arising from Chair", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.15", question: "Gait", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.16", question: "Freezing of Gait", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.17", question: "Postural Stability", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.18", question: "Posture", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.19", question: "Global Spontaneity of Movement", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.20", question: "Postural Tremor (Right)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.21", question: "Postural Tremor (Left)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.22", question: "Kinetic Tremor (Right)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.23", question: "Kinetic Tremor (Left)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.24", question: "Rest Tremor Amplitude (Right Upper)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.25", question: "Rest Tremor Amplitude (Left Upper)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.26", question: "Rest Tremor Amplitude (Right Lower)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.27", question: "Rest Tremor Amplitude (Left Lower)", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "3.28", question: "Constancy of Rest Tremor", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
  ],
  part4: [
    { id: "4.1", question: "Time Spent with Dyskinesias", type: "rater", options: ["None", "1–25%", "26–50%", "51–75%", "76–100%"] },
    { id: "4.2", question: "Functional Impact of Dyskinesias", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "4.3", question: "Time Spent in the Off State", type: "rater", options: ["None", "1–25%", "26–50%", "51–75%", "76–100%"] },
    { id: "4.4", question: "Functional Impact of Fluctuations", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "4.5", question: "Complexity of Motor Fluctuations", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
    { id: "4.6", question: "Painful Off-state Dystonia", type: "rater", options: ["Normal", "Slight", "Mild", "Moderate", "Severe"] },
  ],
};